color0 #282727
color1 #c4746e
color2 #8a9a7b
color3 #c4b28a
color4 #8ba4b0
color5 #a292a3
color6 #8ea4a2
color7 #c5c9c5
color8 #625e5a
color9 #c4746e
color10 #8a9a7b
color11 #b6927b
color12 #8ba4b0
color13 #a292a3
color14 #8ea4a2
color15 #c8c093

cursor                #c5c9c5
cursor_text_color     #181616
background            #181616
foreground            #c5c9c5
selection_foreground  #181616
selection_background  #c5c9c5
active_border_color   #8a9a7b
inactive_border_color #282727
url_color             #8a9a7b

active_tab_foreground   #181616
active_tab_background   #8a9a7b
inactive_tab_foreground #c8c093
inactive_tab_background #282727
cursor_trail_color      #c8c093
